#!/usr/bin/env python3
"""
EDEN & CO. CEO Flight Deck - Orders Cache Builder
Reads local ShipStation CSV and writes src/data/orders-cache.js

Usage: python3 scripts/build-cache.py
Run from the build/ directory.
"""

import csv, json, os, sys, re
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR  = os.path.dirname(SCRIPT_DIR)
CSV_PATH   = os.path.join(BUILD_DIR, '..', 'SKU FIles', 'Stock Tracker - Sales Log.csv')
OUT_PATH   = os.path.join(BUILD_DIR, 'src', 'data', 'orders-cache.js')

def main():
    csv_path = os.path.normpath(CSV_PATH)
    if not os.path.exists(csv_path):
        print(f'ERROR: CSV not found at {csv_path}')
        sys.exit(1)

    # Strategy: REPLACE on every run. Sales Log CSV is the source of truth — always export
    # the full history from ShipStation. The cache is rebuilt from scratch each run.
    # For append-style sources (Google Reviews), see build-marketing-cache.py.
    orders = []
    skipped = 0
    with open(csv_path, newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        for row in reader:
            normalised = {k.strip().replace(' ', '_').upper(): v for k, v in row.items()}
            status = normalised.get('ORDER_STATUS', '').lower()
            if status in ('cancelled', 'canceled'):
                skipped += 1
                continue
            orders.append(normalised)

    print(f'Read {len(orders)} shipped rows from CSV ({skipped} cancelled skipped)')

    # Write JS cache file
    ts = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
    js = f"""// EDEN & CO. CEO Flight Deck - Orders Cache
// Auto-generated by scripts/build-cache.py at {ts}
// Source: Stock Tracker - Sales Log.csv ({len(orders)} rows)
// Re-run build-cache.py after exporting a fresh ShipStation CSV.
window.EDEN = window.EDEN || {{}};
window.EDEN._ordersCache = {json.dumps(orders, separators=(',', ':'))};
window.EDEN._ordersCacheDate = '{ts}';
"""

    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write(js)

    size_kb = os.path.getsize(OUT_PATH) // 1024
    print(f'Written {OUT_PATH} ({size_kb} KB)')

if __name__ == '__main__':
    main()
